#include<iostream>
#include <string>
#include <ctime>
#include <cstdlib>
#include <cmath>
#include <unordered_map>
using namespace std;
class Keys{
    private:
        int p,g;// p n g we get from type 101 message from server, this does need to be stored.
        int privateKey; // Generated by default constructor 
        string roomKey; // Generated by type 104 message or stored by 105
        int publicKey;
        unordered_map <string,int> SharedSecrets,EncryptedRoomMessages; // username and their public key 
        unordered_map<string,string> encryptedRoomMessages; // username and their encrypted room key
    public:
    Keys() {
            privateKey = rand() % 100 + 1; // Random private key between 1 and 100, the probablity of this being 
    }

    string generateroomKey() {// Returns a room key of 26 characters, called on RoomKeygeneration part of type 104 message
        srand(time(NULL));
        roomKey="";
        string chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+-*/!@#$%^&*()_=,.<>?;:[]{}|~!";
        for (int i=0;i<26;i++) {
            roomKey+=chars[rand() % chars.size()];
        }
        return roomKey;
    }

    long modPow(long long base, long long exp, long long mod) {// Diffe hellmans key exchange mod alogorithm for accuracy
        long long result = 1;
        base = base % mod;

        while (exp > 0) {
            if (exp % 2 == 1)
                result = (result * base) % mod;

            base = (base * base) % mod;
            exp /= 2;
        }

        return result;
    }

    int generatePublicKey(int P, int G) {//To be generated on connection and send to server as message lets say 101  
        this->p = P;
        this->g = G;
        this->publicKey = modPow(g, privateKey, p);
        return publicKey;
    }

    string encryptMessage(string message){// XOR ENCRYPTION FOR messages, not the best but works for now, uses Room keys
        string encryptedMessage="";
        for(int i=0; i<message.length();i++){
            encryptedMessage+=message[i] ^ roomKey[i];
        }
        return encryptedMessage;
    }
 
    string decryptMessage(string message,string key){// XOR Decryption for messages
        string decryptedMessage="";
        for(int i=0; i<message.length();i++){
            decryptedMessage+=message[i] ^ key[i];
        }
        return decryptedMessage;
    }
    
    /* On sending a message of type 1, we call roomKeyGenerationAndSharing function alongside provided map of public keys in 
    that type of message. On type 105, We call SetRoomKeyIfNotLeader function which consists of leaderPublicKey and 
    encryptedRoomKey extracted from the unordered map sent by the leader*/

    void SetRoomKeyIfNotLeader(int leaderPublicKey, string encryptedRoomKey){
        int sharedSecret = modPow(leaderPublicKey, privateKey, p);
        this->roomKey= decryptionOfRoomKey(encryptedRoomKey,sharedSecret);
    }

    unordered_map<string,string> roomKeyGenerationAndSharing(unordered_map<string,int> publicKeys) {
        this->roomKey= generateroomKey();
        for (auto it = publicKeys.begin(); it != publicKeys.end(); ++it) {
        string username = it->first;
        int userPublicKey = it->second;
        int sharedSecret = modPow(userPublicKey, privateKey, p);
        SharedSecrets[username] = sharedSecret;
    }
    for(auto it = SharedSecrets.begin(); it!= SharedSecrets.end();++it){
        string username = it->first;
        int sharedSecret = it->second;
        encryptedRoomMessages[username] = RoomKeyEncryption(roomKey,sharedSecret);
    }
    return encryptedRoomMessages;
    }

    string RoomKeyEncryption(string roomKey,int sharedSecret){
        string encryptedRoomKey="";
        for(int i=0; i<roomKey.length();i++){
            encryptedRoomKey+=roomKey[i] ^ sharedSecret;
        }
        return encryptedRoomKey;
    }
    
    string decryptionOfRoomKey(string encryptedRoomKey,int sharedSecret){
        string decryptedRoomKey="";
        for(int i=0; i<encryptedRoomKey.length();i++){
            decryptedRoomKey+=encryptedRoomKey[i] ^ sharedSecret;
        }
        return decryptedRoomKey;
    }
};  
